server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-SECURITY
          uri: lb://USER-SERVICE-SECURITY
          predicates:
            - Path=/auth/**,/home/**

        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/**




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka




